### ISSUE TITLE
Reuqest to use CalendarFX

### ISSUE THREAD

**Issue by arkobrat** [nus-cs2103-AY2223S2/forum#274] opened 2023-03-23 11:12 UTC
## Library

[CalendarFX](https://github.com/dlsc-software-consulting-gmbh/CalendarFX)

## Purpose

To show a calendar view of appointments in the UI.

## License

[Apache-2.0 license](https://github.com/dlsc-software-consulting-gmbh/CalendarFX/blob/master-11/LICENSE)

**Comment by damithc** [comment] 2023-03-23 11:30
Approved (also, duplicate of #205)

**Closed as completed by damithc** 2023-03-23 11:30 UTC
Labels: type-RequestToUseLibrary
