### ISSUE TITLE
Setting up CodeCov

### ISSUE THREAD

**Issue by seadragon2000341** [nus-cs2103-AY2223S2/forum#180] opened 2023-02-13 14:34 UTC
Hello,

I have trouble completing step 3 and 4 below.
For step3, I can't seem to find a way to add to github action workflow.
For step 4, I'm not too sure what they mean by "committing changes in step 2", as well as "ran CI/CD pipeline - are there any specific things that needs to be done in step 4?

Appreciate the help. Thank you!
![image](https://user-images.githubusercontent.com/78403168/218486190-9b012e5c-0ba7-44b1-adfe-f352436195ca.png)

**Comment by damithc** [comment] 2023-02-14 03:21
@seadragon2000341 Are you following https://se-education.org/guides/tutorials/codecov.html ? 
I don't think you need to do the steps you've given in the screenshot.

**Comment by seadragon2000341** [comment] 2023-02-14 13:30
@damithc Hi Prof,

Ok I managed to get codecov to work. But all the pull requests my team members make to the tp repo failed the codecov checks. Is this normal?

![image](https://user-images.githubusercontent.com/78403168/218752979-99e58cdc-ff8a-4d20-80af-f25ded253299.png)

**Comment by hingen** [comment] 2023-02-14 13:38
Hi @seadragon2000341, in the `gradle.yml` file's codecov step, there is a line that is `fail_ci_if_error: false`. This should make it such that even if codecov fails, the Github Action result should still be successful as long as the other steps pass.

Could you perhaps check if the step that failed is indeed the codecov step? You can do so by going to the page for the specific pull request and open the "Checks" tab.
![image](https://user-images.githubusercontent.com/31367001/218754476-c2d8da65-b233-4f7d-9553-6a13a37bba78.png)

**Comment by seadragon2000341** [comment] 2023-02-14 13:56
Hi @Hingen, thanks for your help

I cant seem to find gradle.yml anywhere in the repo

Gradle.yml settings seem good
![image](https://user-images.githubusercontent.com/78403168/218758092-576e4995-3dd7-4c9a-abab-0d8822de1493.png)

One of my friend's failed this check. I failed run-repository wide-tests
![image](https://user-images.githubusercontent.com/78403168/218758615-83e38197-2af4-4d5b-8ff2-4d08a1ef675a.png)

**Comment by hingen** [comment] 2023-02-14 14:22
`gradle.yml` is in the `.github/workflows` directory

Could you get your friend to run `./gradlew check` and `./gradlew coverage` on his/her local repo and see if they fail there? If so, the error message would likely give you an insight as to the cause.

`./gradlew check` can fail due to failing checkstyle or failing JUnit tests.

Not too sure about `./gradlew coverage`, seems to be a custom command defined in the `build.gradle`

**Comment by damithc** [comment] 2023-02-14 14:51
@seadragon2000341 the reason for the CI check failure can usually be found in the CI log. Example from https://github.com/AY2223S2-CS2103T-T14-3/tp/pull/1/checks
![image](https://user-images.githubusercontent.com/1673303/218772790-8428290e-494d-448f-bd85-b41a08363a08.png)

**Comment by seadragon2000341** [comment] 2023-02-16 01:23
Is it a concern if the checks don't pass? For example, the screenshot in your previous comment @damithc

**Comment by damithc** [comment] 2023-02-16 03:17
> Is it a concern if the checks don't pass? For example, the screenshot in your previous comment @damithc

@seadragon2000341 If it is a fixable problem, it is better to fix because checks are their to help you maintain quality. The one in the screenshot is easily fixable.

**Comment by Hikoya** [comment] 2023-02-23 13:26
Hi @seadragon2000341 , I am a senior from a previous batch. Please close the issue if there are no more issues, else please update the post if there are any other errors encountered.

**Closed as completed** 2023-02-23 14:14 UTC
Labels: suitableForPeerHelp, type-HelpRequest :sos:
