### ISSUE TITLE
CheckStyle for switchcases

### ISSUE THREAD

**Issue by homuntan02** [nus-cs2103-AY2223S2/forum#132] opened 2023-02-03 09:44 UTC
For switch case check style, they mentioned the need for a default case. What do I do if I don’t have a default?

**Comment by hingen** [comment] 2023-02-03 11:20
Hi @homuntan02, this was mentioned in CS2103 Week 5

> If there is no default action, you can use the `default` branch to detect errors (i.e. if execution reached the `default` branch, raise a suitable error)

Essentially, if there is nothing to do in the default case, use it as an error checking tool. Should the default case ever be reached, then a bug has most likely occurred in the code. By throwing an exception, and most likely causing the program to crash, it would make it much easier when debugging.

If there is no default case, then there's a chance the code would just execute as per normal even when a bug occurs leading to none of the switch cases matching. This would make it much harder to debug as a user might experience strange behaviour and the dev will most likely have to spend more time digging through the code to try to find the cause.

Read more [here](https://nus-cs2103-ay2223s2.github.io/website/schedule/week5/topics.html#implementation-code-quality-error-prone-practices-basic-use-the-default-branch)

**Comment by adam07018** [comment] 2023-02-06 11:56
I will return immediately or return default value. Worst is to throw exception if default case is impossible

**Comment by damithc** [comment] 2023-02-06 12:08
> I will return immediately or return default value. Worst is to throw exception if default case is impossible

@adam07018 hmm... care to elaborate?

**Comment by homuntan02** [comment] 2023-02-07 02:40
> Hi @homuntan02, this was mentioned in CS2103 Week 5
> 
> > If there is no default action, you can use the `default` branch to detect errors (i.e. if execution reached the `default` branch, raise a suitable error)
> 
> Essentially, if there is nothing to do in the default case, use it as an error checking tool. Should the default case ever be reached, then a bug has most likely occurred in the code. By throwing an exception, and most likely causing the program to crash, it would make it much easier when debugging.
> 
> If there is no default case, then there's a chance the code would just execute as per normal even when a bug occurs leading to none of the switch cases matching. This would make it much harder to debug as a user might experience strange behaviour and the dev will most likely have to spend more time digging through the code to try to find the cause.
> 
> Read more [here](https://nus-cs2103-ay2223s2.github.io/website/schedule/week5/topics.html#implementation-code-quality-error-prone-practices-basic-use-the-default-branch)

Ah that helps a lot thanks!

**Comment by francisyzy** [comment] 2023-02-07 10:34
Hello! It appears that your issue has been resolved 😄

Would you be able to close this issue as completed? This will help us keep the repository organized and up-to-date.

If you think that your question is still not answered, feel free to add a comment to clarify what you would like to know.

Thanks!

**Closed as completed** 2023-02-07 11:50 UTC
Labels: for-Discussion :speech_balloon:, type-Question :thinking:
