### ISSUE TITLE
GUI not appearing when running the program

### ISSUE THREAD

**Issue by jamieeeleow** [nus-cs2103-AY2223S2/forum#131] opened 2023-02-03 09:04 UTC
I followed the instructions given in the JavaFX tutorial and my program ran and worked in the terminal but no GUI appeared.
This was what was shown in the terminal from the command ./gradlew run

```
> Configure project :
Project : => no module-info.java found

> Task :compileJava UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE

> Task :Launcher.main()
```

**Comment by Junyi00** [comment] 2023-02-03 09:32
Pushing your branch for others to test your setup would be helpful here!

**Comment by francisyzy** [comment] 2023-02-03 16:03
- What is your development environment? Ie Windows/Mac/Linux? 
- Have you checked your java version?
- Does exporting a jar file and running it produce a GUI?

**Comment by jamieeeleow** [comment] 2023-02-04 12:29
> * What is your development environment? Ie Windows/Mac/Linux?
> * Have you checked your java version?
> * Does exporting a jar file and running it produce a GUI?

Im using Mac, and running java 11. I've tried exporting a jar file and running it (following the same instructions as that of addressbook.jar) and the program runs in the terminal but still does not produce a GUI

**Comment by damithc** [comment] 2023-02-04 12:33
> Pushing your branch for others to test your setup would be helpful here!

Yup, that could give others a better chance of reproducing the issue and finding a solution.

**Comment by jamieeeleow** [comment] 2023-02-04 17:06
> > Pushing your branch for others to test your setup would be helpful here!
> 
> Yup, that could give others a better chance of reproducing the issue and finding a solution.

Yup I have pushed my branch

**Comment by rexcyrio** [comment] 2023-02-05 01:34
Hi @jamieeeleow

I've cloned your git repo and looked through your code, and here's what I think is happening:

1. The Gradle `run` script is called
1. The `main` function in the `Launcher` class is called
1. A new `Main` object is instantiated
1. Since each `Main` object has a `private Leo leo = new Leo("/data/leo.txt")`, a new `Leo` object is also instantiated
1. The public constructor for the `Leo` class is called
1. `parser.readCommand()` is called
1. The code `String command = scanner.nextLine()` will prevent the execution of any other code as it waits for new user input in the terminal

Point 7 is what I think is causing the GUI to not appear.

When I commented out the `parser.readCommand()` line in the public `Leo` constructor, the GUI appears as expected with the "Hello World!" text.

Hope this helps!

**Comment by damithc** [comment] 2023-02-05 03:10
Thanks for taking time to look through the code, @rexcyrio 💯

**Comment by domlimm** [comment] 2023-02-07 12:00
Hello @jamieeeleow, I'm a senior from a previous batch, dropping by to look at the issues posted by you guys. Just a gentle reminder to close the issue once your problem has been resolved. Have a great day! 😄

**Comment by jamieeeleow** [comment] 2023-02-08 13:26
> Hi @jamieeeleow
> 
> I've cloned your git repo and looked through your code, and here's what I think is happening:
> 
> 1. The Gradle `run` script is called
> 2. The `main` function in the `Launcher` class is called
> 3. A new `Main` object is instantiated
> 4. Since each `Main` object has a `private Leo leo = new Leo("/data/leo.txt")`, a new `Leo` object is also instantiated
> 5. The public constructor for the `Leo` class is called
> 6. `parser.readCommand()` is called
> 7. The code `String command = scanner.nextLine()` will prevent the execution of any other code as it waits for new user input in the terminal
> 
> Point 7 is what I think is causing the GUI to not appear.
> 
> When I commented out the `parser.readCommand()` line in the public `Leo` constructor, the GUI appears as expected with the "Hello World!" text.
> 
> Hope this helps!

Thank you for looking through my code, I managed to get the GUI to appear with your help 😄

**Closed as completed** 2023-02-08 13:27 UTC
Labels: suitableForPeerHelp, type-HelpRequest :sos:

**Comment by damithc** [comment] 2023-02-08 16:11
Thanks for the detailed help, @rexcyrio
